from __future__ import annotations

CURATED_AUTHORITY_TREE = [
    {
        "id": "formation",
        "label_en": "Formation",
        "label_zh": "形成",
        "summary_en": 'Contract coming into existence: agreement, consideration, intention, capacity, and formality.',
        "summary_zh": "合同從無到有的階段：協議、約因、法律約束意圖、行為能力與形式要求。",
        "subgrounds": [
            {
                "id": "agreement",
                "label_en": "Agreement",
                "label_zh": "協議",
                "summary_en": "Objective consensus, including offer, acceptance, and certainty.",
                "summary_zh": "客觀合意，包括要約、接受與協議確定性。",
                "topic_labels": [
                    "Agreement (Offer and Acceptance)",
                    "Offer vs. Invitation to Treat",
                    "Communication of Acceptance",
                ],
                "children": [
                    {"en": "Offer vs. invitation to treat", "zh": "要約與邀請要約的區分"},
                    {"en": "Rules of acceptance", "zh": "接受的規則"},
                    {"en": "Certainty of agreement", "zh": "協議確定性"},
                ],
            },
            {
                "id": "consideration",
                "label_en": "Consideration",
                "label_zh": "約因",
                "summary_en": "Exchange of value and the enforceability of variations.",
                "summary_zh": "價值交換與合同變更可執行性。",
                "topic_labels": ["Consideration"],
                "children": [],
            },
            {
                "id": "intention",
                "label_en": "Intention to Create Legal Relations",
                "label_zh": "法律約束意圖",
                "summary_en": "Whether the parties objectively intended legal enforceability.",
                "summary_zh": "當事人是否客觀上意圖產生法律約束力。",
                "topic_labels": ["Intention to Create Legal Relations"],
                "children": [],
            },
            {
                "id": "capacity",
                "label_en": "Capacity",
                "label_zh": "行為能力",
                "summary_en": "Who may contract and on what terms.",
                "summary_zh": "誰有能力訂立合同，以及能力限制如何影響效力。",
                "topic_labels": ["Capacity"],
                "children": [],
            },
            {
                "id": "formality",
                "label_en": "Formality",
                "label_zh": "形式要求",
                "summary_en": "Writing, signature, and formal validity requirements.",
                "summary_zh": "書面、簽署與形式有效性要求。",
                "topic_labels": ["Formality"],
                "children": [],
            },
        ],
    },
    {
        "id": "contents",
        "label_en": "Contents",
        "label_zh": "內容",
        "summary_en": "What the contract says, how its terms are identified, interpreted, implied, classified, and controlled.",
        "summary_zh": "合同內容為何：條款如何識別、解釋、默示、分類與控制。",
        "subgrounds": [
            {
                "id": "term_identification",
                "label_en": "Term Identification",
                "label_zh": "條款識別",
                "summary_en": "Express terms, representations, and the parol evidence rule.",
                "summary_zh": "明示條款、陳述與口頭證據規則。",
                "topic_labels": ["Express Terms and the Parol Evidence Rule"],
                "children": [
                    {"en": "Express terms vs representations", "zh": "明示條款與陳述的區分"},
                    {"en": "Parol evidence rule", "zh": "口頭證據規則"},
                ],
            },
            {
                "id": "interpretation",
                "label_en": "Interpretation",
                "label_zh": "條款解釋",
                "summary_en": "Objective interpretation and the context-versus-text lineage.",
                "summary_zh": "客觀解釋原則，以及文本與語境之間的權威發展路徑。",
                "topic_labels": ["Express Terms and the Parol Evidence Rule"],
                "lineage_ids": ["interpretation_context_text"],
                "children": [
                    {"en": "Objective interpretation", "zh": "客觀解釋原則"},
                    {"en": "ICS / Sinoearn / Arnold / Wood line", "zh": "ICS / Sinoearn / Arnold / Wood 發展脈絡"},
                ],
            },
            {
                "id": "implied_terms",
                "label_en": "Implied Terms",
                "label_zh": "默示條款",
                "summary_en": "Terms implied in fact, in law, by statute, or by custom.",
                "summary_zh": "事實默示、法律默示、成文法默示與慣例默示。",
                "topic_labels": ["Implied Terms", "Statutory Implied Terms"],
                "children": [
                    {"en": "Implied in fact", "zh": "事實默示"},
                    {"en": "Implied in law", "zh": "法律默示"},
                    {"en": "Implied by statute", "zh": "成文法默示"},
                    {"en": "Implied by custom", "zh": "慣例默示"},
                ],
            },
            {
                "id": "classification",
                "label_en": "Term Classification",
                "label_zh": "條款分類",
                "summary_en": "Condition, warranty, and innominate term analysis.",
                "summary_zh": "條件、保證與中間條款分析。",
                "topic_labels": [
                    "Classification of Terms",
                    "Conditions",
                    "Warranties",
                    "Innominate (Intermediate) Terms",
                ],
                "lineage_ids": ["intermediate_terms_hongkong_fir"],
                "children": [
                    {"en": "Conditions", "zh": "條件"},
                    {"en": "Warranties", "zh": "保證"},
                    {"en": "Innominate terms", "zh": "中間條款"},
                ],
            },
            {
                "id": "exemption_clauses",
                "label_en": "Exemption Clauses",
                "label_zh": "免責條款",
                "summary_en": "Construction, contra proferentem, and statutory control.",
                "summary_zh": "解釋原則、不利起草者解釋規則與成文法控制。",
                "topic_labels": ["Exemption Clauses", "Statutory Control of Exemption Clauses"],
                "children": [
                    {"en": "Common law construction", "zh": "普通法解釋原則"},
                    {"en": "Statutory control", "zh": "成文法控制"},
                ],
            },
        ],
    },
    {
        "id": "vitiating_factors",
        "label_en": "Vitiating Factors",
        "label_zh": "效力瑕疵",
        "summary_en": "Reasons why an apparent contract may be void, voidable, or unenforceable.",
        "summary_zh": "為何表面成立的合同可能無效、可撤銷或不可執行。",
        "subgrounds": [
            {
                "id": "misrepresentation",
                "label_en": "Misrepresentation",
                "label_zh": "失實陳述",
                "summary_en": "False statements inducing entry into contract.",
                "summary_zh": "引致訂約的虛假陳述。",
                "topic_labels": ["Misrepresentation"],
                "children": [],
            },
            {
                "id": "mistake",
                "label_en": "Mistake",
                "label_zh": "錯誤",
                "summary_en": "Common, mutual, and unilateral mistake.",
                "summary_zh": "共同錯誤、相互錯誤與單方錯誤。",
                "topic_labels": ["Mistake"],
                "children": [],
            },
            {
                "id": "duress",
                "label_en": "Duress",
                "label_zh": "脅迫",
                "summary_en": "Physical and economic pressure undermining consent.",
                "summary_zh": "人身或經濟壓力導致同意受損。",
                "topic_labels": ["Duress"],
                "children": [],
            },
            {
                "id": "undue_influence",
                "label_en": "Undue Influence",
                "label_zh": "不當影響",
                "summary_en": "Improper influence and the Etridge adoption line.",
                "summary_zh": "不當影響與 Etridge 在香港的採納路徑。",
                "topic_labels": ["Undue Influence"],
                "lineage_ids": ["undue_influence_etridge"],
                "children": [],
            },
            {
                "id": "unconscionability",
                "label_en": "Unconscionability",
                "label_zh": "不合情理",
                "summary_en": "Common law and statutory unfairness control.",
                "summary_zh": "普通法與成文法下的不公控制。",
                "topic_labels": ["Unconscionability"],
                "lineage_ids": ["unconscionability_statutory"],
                "children": [],
            },
            {
                "id": "illegality",
                "label_en": "Illegality",
                "label_zh": "非法性",
                "summary_en": "Illegality in formation or performance.",
                "summary_zh": "訂立時非法或履行時非法。",
                "topic_labels": ["Illegality"],
                "children": [],
            },
        ],
    },
    {
        "id": "termination",
        "label_en": "Termination",
        "label_zh": "終止",
        "summary_en": "When and how contractual obligations come to an end.",
        "summary_zh": "合同義務何時以及如何終止。",
        "subgrounds": [
            {
                "id": "performance",
                "label_en": "Performance",
                "label_zh": "履行完畢",
                "summary_en": "Discharge by full or sufficient performance.",
                "summary_zh": "因完全或充分履行而解除。",
                "topic_labels": ["By Performance"],
                "children": [],
            },
            {
                "id": "agreement_termination",
                "label_en": "Termination by Agreement",
                "label_zh": "協議終止",
                "summary_en": "Current graph placeholder. Refine with HKLII if distinct rescission or mutual discharge authorities are needed.",
                "summary_zh": "當前圖譜中的佔位結構；如需明確解除或雙方同意終止的香港權威，可由 HKLII 補強。",
                "topic_labels": [],
                "children": [],
            },
            {
                "id": "repudiatory_breach",
                "label_en": "Repudiatory Breach",
                "label_zh": "違約終止",
                "summary_en": "Termination for serious breach or renunciation.",
                "summary_zh": "因根本違約或毀約表態而終止。",
                "topic_labels": ["By Breach"],
                "children": [],
            },
            {
                "id": "frustration",
                "label_en": "Frustration",
                "label_zh": "合同受挫",
                "summary_en": "Supervening events preventing or radically transforming performance.",
                "summary_zh": "後發事件阻止履行或使履行發生根本變化。",
                "topic_labels": ["By Frustration"],
                "children": [],
            },
        ],
    },
    {
        "id": "remedies",
        "label_en": "Remedies",
        "label_zh": "救濟",
        "summary_en": "Consequences of breach and the available legal or equitable responses.",
        "summary_zh": "違約後的後果，以及普通法與衡平法下可獲得的救濟。",
        "subgrounds": [
            {
                "id": "damages",
                "label_en": "Damages",
                "label_zh": "損害賠償",
                "summary_en": "Expectation, reliance, remoteness, and liquidated damages versus penalties.",
                "summary_zh": "預期利益、信賴利益、可預見性，以及約定賠償金與罰金。",
                "topic_labels": [
                    "Unliquidated Damages",
                    "Remoteness of Damage",
                    "Liquidated Damages vs. Penalties",
                ],
                "lineage_ids": ["penalty_clauses_modern_test"],
                "children": [
                    {"en": "Expectation vs reliance", "zh": "預期利益與信賴利益"},
                    {"en": "Hadley v Baxendale remoteness", "zh": "Hadley v Baxendale 可預見性規則"},
                    {"en": "Liquidated damages vs penalties", "zh": "約定賠償金與罰金"},
                ],
            },
            {
                "id": "equitable_remedies",
                "label_en": "Equitable Remedies",
                "label_zh": "衡平法救濟",
                "summary_en": "Specific performance and injunctions.",
                "summary_zh": "強制履行與禁制令。",
                "topic_labels": ["Equitable Remedies"],
                "children": [
                    {"en": "Specific performance", "zh": "強制履行"},
                    {"en": "Injunctions", "zh": "禁制令"},
                ],
            },
        ],
    },
    {
        "id": "privity",
        "label_en": "Privity",
        "label_zh": "相對性",
        "summary_en": "Who may sue or rely on contractual rights.",
        "summary_zh": "誰可以主張合同權利或依賴合同利益。",
        "subgrounds": [
            {
                "id": "common_law_privity",
                "label_en": "Common Law Principle",
                "label_zh": "普通法原則",
                "summary_en": "Current graph placeholder for the privity baseline; refine with primary authorities.",
                "summary_zh": "當前圖譜中的相對性基線佔位節點；可由主要判例進一步補強。",
                "topic_labels": [],
                "children": [],
            },
            {
                "id": "statutory_exceptions",
                "label_en": "Statutory Exceptions",
                "label_zh": "成文法例外",
                "summary_en": "Contracts (Rights of Third Parties) Ordinance and related exceptions.",
                "summary_zh": "《合約（第三者權利）條例》及相關例外。",
                "topic_labels": ["Statutory Exceptions"],
                "children": [
                    {"en": "Cap. 623", "zh": "第 623 章"},
                ],
            },
        ],
    },
    {
        "id": "special_contracts",
        "label_en": "Special Contracts",
        "label_zh": "特殊合同類型",
        "summary_en": "Contract doctrine applied in recurrent subject-matter areas.",
        "summary_zh": "合同法在反覆出現的特定交易領域中的適用。",
        "subgrounds": [
            {
                "id": "sale_of_goods",
                "label_en": "Sale of Goods",
                "label_zh": "貨物買賣",
                "summary_en": "Sale of goods, transfer of title, and statutory implied terms.",
                "summary_zh": "貨物買賣、所有權轉移與成文法默示條款。",
                "topic_labels": ["Sale of Goods and Services"],
                "children": [],
            },
            {
                "id": "supply_of_services",
                "label_en": "Supply of Services",
                "label_zh": "服務提供",
                "summary_en": "Reasonable skill, care, time, and charges in service contracts.",
                "summary_zh": "服務合同中的合理技能、謹慎、時間與收費。",
                "topic_labels": ["Sale of Goods and Services"],
                "children": [],
            },
            {
                "id": "sale_of_land",
                "label_en": "Sale of Land",
                "label_zh": "土地買賣",
                "summary_en": "Land sale formalities and interim sale agreements.",
                "summary_zh": "土地交易的形式要求與臨時買賣協議。",
                "topic_labels": ["Sale of Land and Leases"],
                "children": [],
            },
            {
                "id": "employment",
                "label_en": "Employment Contracts",
                "label_zh": "僱傭合同",
                "summary_en": "Service contracts, worker status, and relational obligations.",
                "summary_zh": "服務合同、勞動者身分與關係性義務。",
                "topic_labels": ["Employment Contracts"],
                "children": [],
            },
            {
                "id": "construction",
                "label_en": "Construction Contracts",
                "label_zh": "建設工程合同",
                "summary_en": "Standard forms, certification, and contractual variation in construction.",
                "summary_zh": "標準格式、認證與建設工程中的合同變更。",
                "topic_labels": ["Construction Contracts"],
                "children": [],
            },
            {
                "id": "credit_security",
                "label_en": "Credit, Security, and Guarantees",
                "label_zh": "信貸與擔保",
                "summary_en": "Security devices, guarantees, and finance-related obligations.",
                "summary_zh": "擔保工具、保證與融資合同義務。",
                "topic_labels": ["Credit, Security, and Guarantees"],
                "children": [],
            },
            {
                "id": "insurance",
                "label_en": "Insurance Contracts",
                "label_zh": "保險合同",
                "summary_en": "Utmost good faith and insurable interest issues.",
                "summary_zh": "最高誠信義務與可保利益問題。",
                "topic_labels": ["Insurance Contracts"],
                "children": [],
            },
        ],
    },
    {
        "id": "cross_cutting",
        "label_en": "Cross-Cutting Issues",
        "label_zh": "跨界議題",
        "summary_en": "Technology, cross-border, and procedure-focused overlays on contract doctrine.",
        "summary_zh": "技術、跨境與程序性議題對合同法的橫向覆蓋。",
        "subgrounds": [
            {
                "id": "electronic_contracting",
                "label_en": "Electronic Contracting and Emerging Technology",
                "label_zh": "電子合同與新興技術",
                "summary_en": "Clickwrap, browsewrap, smart contracts, and privacy-related contract issues.",
                "summary_zh": "點擊協議、瀏覽協議、智能合約與數據隱私相關合同問題。",
                "topic_labels": ["Electronic Contracting", "Smart Contracts & Blockchain", "Data Privacy in Contracts"],
                "children": [],
            },
            {
                "id": "cross_border_contracts",
                "label_en": "Cross-Border Contracts",
                "label_zh": "跨境合同",
                "summary_en": "Choice of law, jurisdiction, and foreign illegality treatment.",
                "summary_zh": "法律選擇、管轄權與外國法下非法性的處理。",
                "topic_labels": ["Choice of Law", "Long-Arm Jurisdiction", "Foreign Illegality"],
                "children": [],
            },
            {
                "id": "dispute_resolution",
                "label_en": "Dispute Resolution",
                "label_zh": "爭議解決",
                "summary_en": "Arbitration and mediation as contract-related dispute mechanisms.",
                "summary_zh": "以仲裁與調解處理合同爭議。",
                "topic_labels": ["Arbitration", "Mediation"],
                "children": [],
            },
        ],
    },
]
