from __future__ import annotations

CURATED_CASE_ENRICHMENTS = [
    {
        "neutral_citation": "[1999] HKCFI 1007",
        "parallel_citations": [],
        "case_name": "Chiu Man On Paul t/a Pacific Power Engineering Co. v Vaford Contracting Co. Ltd.",
        "short_name": "Chiu Man On Paul v Vaford Contracting",
        "court_code": "HKCFI",
        "court_name": "Court of First Instance",
        "court_level": "CFI",
        "decision_date": "1999-10-20",
        "judges": ["Cheung J"],
        "source_links": [
            {"label": "HKLII Link", "url": "https://www.hklii.hk/en/cases/hkcfi/1999/1007"},
        ],
        "summary_en": "Hong Kong implied-terms decision applying BP Refinery, objective interpretation, and a practical implied term to avoid payment deadlock.",
        "summary_zh": "關於默示條款、客觀合同解釋及付款僵局默示條款的香港判例。",
        "topic_hints": ["Implied Terms", "Interpretation"],
        "principles": [
            {
                "paragraph_span": "§8-10",
                "para_start": 8,
                "para_end": 10,
                "label_en": "Implied terms and business efficacy",
                "label_zh": "默示條款與商業效用",
                "statement_en": "A term is only implied where the contract lacks business efficacy without it; if the agreement still works, implication is not justified.",
                "statement_zh": "只有在合同若無該條款便無法具有商業效用時，法院才會默示條款；若合同在沒有該條款時仍然有效，則不應默示。",
                "cited_authority": {
                    "type": "case",
                    "label": "B.P. Refinery (Westernport) Pty. Ltd. v Shire of Hastings [1977] 16 ALR 363",
                },
            },
            {
                "paragraph_span": "§9",
                "para_start": 9,
                "para_end": 9,
                "label_en": "Objective background principle",
                "label_zh": "客觀背景事實原則",
                "statement_en": "Implication must be assessed against the background facts known to both parties at the time of contracting.",
                "statement_zh": "默示條款的認定需以訂立合同時雙方已知的所有背景事實為依據。",
                "cited_authority": {
                    "type": "case",
                    "label": "Investors Compensation Scheme Ltd. v West Bromwich Building Society [1998] 1 WLR 896",
                },
            },
            {
                "paragraph_span": "§17-18",
                "para_start": 17,
                "para_end": 18,
                "label_en": "Payment deadlock implication",
                "label_zh": "付款僵局默示條款",
                "statement_en": "Where the contract omits the trigger for payment, the court may imply a reasonable-time mechanism to keep the bargain workable.",
                "statement_zh": "當合同未約定付款觸發條件時，法院可默示合理時間機制，以避免合同在付款問題上無法執行。",
                "cited_authority": None,
            },
        ],
        "relationships": [
            {
                "type": "FOLLOWS",
                "target_type": "case",
                "target_label": "B.P. Refinery (Westernport) Pty. Ltd. v Shire of Hastings [1977] 16 ALR 363",
                "description": "Adopts the BP Refinery five-factor test for implying terms in fact.",
            },
            {
                "type": "APPLIES",
                "target_type": "case",
                "target_label": "Investors Compensation Scheme Ltd. v West Bromwich Building Society [1998] 1 WLR 896",
                "description": "Applies the objective interpretation principle to implication analysis.",
            },
        ],
    },
    {
        "neutral_citation": "[2018] HKCFI 1506",
        "parallel_citations": ["[2018] 3 HKLRD 370"],
        "case_name": "To Yung Sing Herman v Szeto Chak Mei and Others",
        "short_name": "To Yung Sing Herman v Szeto Chak Mei",
        "court_code": "HKCFI",
        "court_name": "Court of First Instance",
        "court_level": "CFI",
        "decision_date": "2018-07-04",
        "judges": ["Lisa Wong J"],
        "source_links": [
            {"label": "HKLII Link", "url": "https://hklii.hk/en/cases/hkcfi/2018/1506"},
        ],
        "summary_en": "Land-sale decision on vacant possession, title proof under Cap. 219, and holistic contractual interpretation.",
        "summary_zh": "關於土地買賣合同、空置管有權及整體性合同解釋的香港判例。",
        "topic_hints": ["Interpretation", "Special Contracts"],
        "principles": [
            {
                "paragraph_span": "§8",
                "para_start": 8,
                "para_end": 8,
                "label_en": "Vacant possession and good title",
                "label_zh": "空置管有權與良好所有權",
                "statement_en": "A vendor must deliver vacant possession and prove good title under sections 13 and 13A of the Conveyancing and Property Ordinance.",
                "statement_zh": "賣方須在交房時交付空置管有權，並按《物業轉易及財產條例》第13及13A條證明良好所有權。",
                "cited_authority": {
                    "type": "statute",
                    "label": "Conveyancing and Property Ordinance (Cap 219) ss. 13, 13A",
                },
            },
            {
                "paragraph_span": "§10-12",
                "para_start": 10,
                "para_end": 12,
                "label_en": "Objective test for vacant possession",
                "label_zh": "空置管有權的客觀認定",
                "statement_en": "If substantial debris or objects prevent normal use of the premises, vacant possession has not been delivered.",
                "statement_zh": "若單元內遺留大量雜物或垃圾，導致無法正常使用，即構成未交付空置管有權。",
                "cited_authority": None,
            },
            {
                "paragraph_span": "§36",
                "para_start": 36,
                "para_end": 36,
                "label_en": "Holistic interpretation",
                "label_zh": "合同解釋的整體性原則",
                "statement_en": "Contractual clauses should be read as a whole rather than in isolation.",
                "statement_zh": "合同條款應作整體解釋，不能孤立看待單一條款。",
                "cited_authority": None,
            },
        ],
        "relationships": [
            {
                "type": "INTERPRETS",
                "target_type": "statute",
                "target_label": "Conveyancing and Property Ordinance (Cap 219) ss. 13, 13A",
                "description": "Explains the vendor's title-proof obligations in a land-sale contract.",
            },
        ],
    },
    {
        "neutral_citation": "[1988] HKCFI 257",
        "parallel_citations": [],
        "case_name": "Siemsgluss & Sohn v Yiu Shui Ching Anita t/a Everise Trading Co.",
        "short_name": "Siemsgluss & Sohn v Yiu Shui Ching Anita",
        "court_code": "HKCFI",
        "court_name": "High Court (now Court of First Instance)",
        "court_level": "CFI",
        "decision_date": "1988-11-11",
        "judges": ["Deputy Judge Sharwood"],
        "source_links": [
            {"label": "HKLII Link", "url": "https://www.hklii.org/en/cases/hkcfi/1988/257"},
        ],
        "summary_en": "Variation and settlement case on rescission by agreement, evidential proof of variation, and forbearance as good consideration.",
        "summary_zh": "關於協議解除、合同變更證明及忍讓訴訟作為有效約因的香港判例。",
        "topic_hints": ["Consideration", "Termination by Agreement"],
        "principles": [
            {
                "paragraph_span": "§20-21",
                "para_start": 20,
                "para_end": 21,
                "label_en": "Independent rescission bargain",
                "label_zh": "解除原合同的新約定",
                "statement_en": "The parties may discharge the original contract by agreeing on a fixed compensation arrangement that stands as a new bargain.",
                "statement_zh": "雙方可協議以支付固定賠償金的方式解除原合同，該安排可構成獨立的新約定。",
                "cited_authority": None,
            },
            {
                "paragraph_span": "§26",
                "para_start": 26,
                "para_end": 26,
                "label_en": "Proof of contractual variation",
                "label_zh": "合同變更的證明要求",
                "statement_en": "A party alleging a later variation must prove clear agreement by oral or written evidence.",
                "statement_zh": "若一方主張合同已被新協議變更，須有明確的書面或口頭證據證明已達成合意。",
                "cited_authority": None,
            },
            {
                "paragraph_span": "§17-18",
                "para_start": 17,
                "para_end": 18,
                "label_en": "Forbearance as consideration",
                "label_zh": "忍讓訴訟作為約因",
                "statement_en": "Foregoing a damages claim in exchange for a fixed payment can amount to sufficient consideration.",
                "statement_zh": "一方放棄追索違約損失，換取對方支付固定賠償金，可構成有效約因。",
                "cited_authority": {
                    "type": "case",
                    "label": "Chappel & Co Ltd v Nestle Co Ltd [1960]",
                },
            },
        ],
        "relationships": [
            {
                "type": "APPLIES",
                "target_type": "case",
                "target_label": "Chappel & Co Ltd v Nestle Co Ltd [1960]",
                "description": "Uses the sufficiency-not-adequacy approach to consideration.",
            },
        ],
    },
    {
        "neutral_citation": "[2006] HKCFI 534",
        "parallel_citations": [],
        "case_name": "Travelex Hong Kong Ltd v Ettore Nassetti (Asia) Ltd",
        "short_name": "Travelex Hong Kong Ltd v Ettore Nassetti",
        "court_code": "HKCFI",
        "court_name": "Court of First Instance",
        "court_level": "CFI",
        "decision_date": "2006-06-02",
        "judges": ["Deputy Judge Gill"],
        "source_links": [
            {"label": "HKLII Link", "url": "https://www.hklii.hk/en/cases/hkcfi/2006/534"},
        ],
        "summary_en": "Misrepresentation case stressing proof, the weight of recordings, and the binding force of signed standard terms.",
        "summary_zh": "關於失實陳述抗辯、錄音證據及標準格式合同效力的香港判例。",
        "topic_hints": ["Misrepresentation", "Express Terms and the Parol Evidence Rule"],
        "principles": [
            {
                "paragraph_span": "§10-11, §21",
                "para_start": 10,
                "para_end": 21,
                "label_en": "Burden of proving oral misrepresentation",
                "label_zh": "口頭失實陳述的證明責任",
                "statement_en": "A party alleging inducement by oral statements must provide clear and credible evidence; recordings are especially weighty.",
                "statement_zh": "主張被對方口頭陳述誤導而訂立合同的一方，須提供清晰可信的證據；錄音尤其重要。",
                "cited_authority": None,
            },
            {
                "paragraph_span": "§23-25",
                "para_start": 23,
                "para_end": 25,
                "label_en": "Primacy of recordings",
                "label_zh": "錄音證據的優先性",
                "statement_en": "Where negotiations were recorded, the recording outweighs the parties' later recollections.",
                "statement_zh": "當關鍵口頭交涉內容被錄音時，錄音記錄優先於當事人的事後記憶。",
                "cited_authority": None,
            },
            {
                "paragraph_span": "§1, §26",
                "para_start": 1,
                "para_end": 26,
                "label_en": "Binding force of standard-form terms",
                "label_zh": "標準格式合同的約束力",
                "statement_en": "Signed standard-form trading terms bind the parties absent fraud or actionable misrepresentation.",
                "statement_zh": "在商業交易中，雙方簽署的標準格式合同條款對雙方具有約束力，除非存在欺詐或失實陳述。",
                "cited_authority": {
                    "type": "case",
                    "label": "Derry v Peek (1889)",
                },
            },
        ],
        "relationships": [
            {
                "type": "APPLIES",
                "target_type": "case",
                "target_label": "Derry v Peek (1889)",
                "description": "Applies the classic fraud standard when assessing the pleaded misrepresentation case.",
            },
        ],
    },
    {
        "neutral_citation": "[2021] HKCFA 14",
        "parallel_citations": [],
        "case_name": "Re Hsin Chong Construction Co., Ltd.",
        "short_name": "Re Hsin Chong Construction",
        "court_code": "HKCFA",
        "court_name": "Court of Final Appeal",
        "court_level": "CFA",
        "decision_date": "2021-01-01",
        "judges": [],
        "source_links": [
            {"label": "Case Summary", "url": "https://www.onc.hk/en_US/publication/re-hsin-chong-construction-company-limited"},
        ],
        "summary_en": "CFA winding-up decision on the strict operation of section 182, the meaning of company property, and validation-order standards.",
        "summary_zh": "終審法院就《公司（清盤及雜項條文）條例》第182條、公司財產及驗證令標準作出的權威判決。",
        "topic_hints": ["Interpretation", "Cross-Cutting Issues"],
        "principles": [
            {
                "paragraph_span": "",
                "para_start": None,
                "para_end": None,
                "label_en": "Strict effect of section 182",
                "label_zh": "第182條的嚴格適用",
                "statement_en": "After the commencement of winding up, any disposition of company property is void unless the court otherwise orders.",
                "statement_zh": "清盤開始後對公司財產的任何處置，除非法院另有命令，否則無效。",
                "cited_authority": {
                    "type": "statute",
                    "label": "Companies (Winding Up and Miscellaneous Provisions) Ordinance (Cap 32) s.182",
                },
            },
            {
                "paragraph_span": "",
                "para_start": None,
                "para_end": None,
                "label_en": "Contractual rights as property",
                "label_zh": "合同權利屬公司財產",
                "statement_en": "Rights under a contract remain company property even after they are converted into a payment claim.",
                "statement_zh": "合同項下的權利屬於公司財產，即使其後被轉化為付款請求權亦然。",
                "cited_authority": None,
            },
            {
                "paragraph_span": "",
                "para_start": None,
                "para_end": None,
                "label_en": "Validation-order standard",
                "label_zh": "驗證令的批准標準",
                "statement_en": "A validation order should only be granted where the disposition benefits the body of unsecured creditors as a whole.",
                "statement_zh": "只有在處置行為對全體無擔保債權人有利時，法院才會批准驗證令。",
                "cited_authority": None,
            },
        ],
        "relationships": [
            {
                "type": "INTERPRETS",
                "target_type": "statute",
                "target_label": "Companies (Winding Up and Miscellaneous Provisions) Ordinance (Cap 32) s.182",
                "description": "Provides the CFA's authoritative construction of section 182.",
            },
        ],
    },
    {
        "neutral_citation": "[2025] HKCA 1129",
        "parallel_citations": [],
        "case_name": "MG Charter Ltd v Beijing Caissa International Travel Service Co., Ltd",
        "short_name": "MG Charter Ltd v Beijing Caissa",
        "court_code": "HKCA",
        "court_name": "Court of Appeal",
        "court_level": "CA",
        "decision_date": "2025-01-01",
        "judges": [],
        "source_links": [
            {"label": "Judiciary Link", "url": "https://legalref.judiciary.hk/lrs/common/ju/ju_frame.jsp?DIS=175470"},
        ],
        "summary_en": "Court of Appeal decision distinguishing formation and performance conditions precedent and reaffirming holistic commercial interpretation.",
        "summary_zh": "上訴法院關於合同成立條件先例、履行條件先例及商業合理性解釋的判例。",
        "topic_hints": ["Agreement (Offer and Acceptance)", "Interpretation"],
        "principles": [
            {
                "paragraph_span": "§36-38",
                "para_start": 36,
                "para_end": 38,
                "label_en": "Formation versus performance conditions precedent",
                "label_zh": "成立與履行條件先例的區分",
                "statement_en": "A condition precedent to formation determines whether a contract exists; a condition precedent to performance suspends obligations under an already-formed contract.",
                "statement_zh": "合同成立的條件先例決定合同是否成立；履行的條件先例則是在合同已成立後暫緩履行義務。",
                "cited_authority": None,
            },
            {
                "paragraph_span": "§43-46",
                "para_start": 43,
                "para_end": 46,
                "label_en": "Whole-contract interpretation",
                "label_zh": "整體性合同解釋",
                "statement_en": "Interpretation requires reading all contractual provisions together rather than isolating one clause.",
                "statement_zh": "解釋合同不能孤立看待某一條款，必須將所有條款作為一個整體考慮。",
                "cited_authority": None,
            },
            {
                "paragraph_span": "§46-47, §49",
                "para_start": 46,
                "para_end": 49,
                "label_en": "Commercial reasonableness and background facts",
                "label_zh": "商業合理性與背景事實",
                "statement_en": "The court should resist commercially unreasonable readings and may still use background facts even where an entire-agreement clause exists.",
                "statement_zh": "解釋合約時應避免導致商業上不合理的結果；即使有完整合約條款，仍可援引背景事實協助解釋。",
                "cited_authority": {
                    "type": "case",
                    "label": "Investors Compensation Scheme Ltd. v West Bromwich Building Society [1998] 1 WLR 896",
                },
            },
        ],
        "relationships": [
            {
                "type": "APPLIES",
                "target_type": "case",
                "target_label": "Investors Compensation Scheme Ltd. v West Bromwich Building Society [1998] 1 WLR 896",
                "description": "Applies the background-facts principle in contractual interpretation.",
            },
            {
                "type": "DISTINGUISHES",
                "target_type": "case",
                "target_label": "[2022] HKCFI 3672",
                "description": "Distinguishes the first-instance approach to conditions precedent.",
            },
        ],
    },
    {
        "neutral_citation": "[2020] HKCFI 600",
        "parallel_citations": [],
        "case_name": "Wong Yee Chuk v Lo Po Wai, Harry and Others",
        "short_name": "Wong Yee Chuk v Lo Po Wai",
        "court_code": "HKCFI",
        "court_name": "Court of First Instance",
        "court_level": "CFI",
        "decision_date": "2020-04-16",
        "judges": ["Harris J"],
        "source_links": [
            {"label": "WorldLII Link", "url": "http://www.worldlii.org/hk/cases/hkcfi/2020/600.html"},
        ],
        "summary_en": "Settlement-formation case reaffirming mirror acceptance and the counter-offer rule in written compromise negotiations.",
        "summary_zh": "關於和解協議成立及反要約原則的香港判例。",
        "topic_hints": ["Agreement (Offer and Acceptance)"],
        "principles": [
            {
                "paragraph_span": "§6-8",
                "para_start": 6,
                "para_end": 8,
                "label_en": "Formation of a settlement agreement",
                "label_zh": "和解協議的成立",
                "statement_en": "A binding settlement is formed when one side offers clear written terms and the other accepts them in writing without introducing new conditions.",
                "statement_zh": "一方以書面提出明確和解條款，另一方以書面接受且未加入新條件時，即成立有約束力的和解協議。",
                "cited_authority": None,
            },
            {
                "paragraph_span": "§8",
                "para_start": 8,
                "para_end": 8,
                "label_en": "Mirror acceptance",
                "label_zh": "無增無減接受原則",
                "statement_en": "Acceptance must mirror the offer, with no less and no more; additions or alterations amount to a counter-offer.",
                "statement_zh": "接受必須與要約條款完全一致，無增無減；任何添加或修改都構成反要約。",
                "cited_authority": {
                    "type": "case",
                    "label": "Hyde v Wrench (1840)",
                },
            },
        ],
        "relationships": [
            {
                "type": "APPLIES",
                "target_type": "case",
                "target_label": "Hyde v Wrench (1840)",
                "description": "Applies the classic counter-offer principle to settlement correspondence.",
            },
        ],
    },
    {
        "neutral_citation": "[2023] HKCFI 1327",
        "parallel_citations": [],
        "case_name": "Eton Properties Ltd and Eton Properties Holdings Ltd v Xiamen Xinjingdi Group Co., Ltd",
        "short_name": "Eton Properties v Xiamen Xinjingdi",
        "court_code": "HKCFI",
        "court_name": "Court of First Instance",
        "court_level": "CFI",
        "decision_date": "2023-05-18",
        "judges": ["Mimmie Chan J"],
        "source_links": [
            {
                "label": "Jus Mundi Link",
                "url": "https://jusmundi.com/en/document/decision/en-eton-properties-ltd-and-eton-properties-holdings-ltd-v-xiamen-xinjingdi-group-co-ltd-judgment-of-the-court-of-first-instance-of-the-high-court-of-hong-kong-2023-hkcfi-1327",
            },
        ],
        "summary_en": "Judgment on mala fide repeat proceedings, issue estoppel, and the Henderson v Henderson abuse principle.",
        "summary_zh": "關於惡意重複程序、既判力及 Henderson v Henderson 原則的香港判例。",
        "topic_hints": ["Cross-Border Contracts", "Dispute Resolution"],
        "principles": [
            {
                "paragraph_span": "§9-11",
                "para_start": 9,
                "para_end": 11,
                "label_en": "Mala fide repeat proceedings",
                "label_zh": "惡意重複程序",
                "statement_en": "Launching new proceedings in another forum after final Hong Kong determinations can be mala fide where it reopens matters already decided.",
                "statement_zh": "在香港已有終局判決後，若一方在其他法域啟動新程序以重新爭議既決事項，可構成惡意程序。",
                "cited_authority": None,
            },
            {
                "paragraph_span": "§12-19",
                "para_start": 12,
                "para_end": 19,
                "label_en": "Res judicata and issue estoppel",
                "label_zh": "既判力與爭點禁反言",
                "statement_en": "Issues resolved by arbitral awards or court judgments should not be re-litigated.",
                "statement_zh": "仲裁裁決和法院判決已確定的事項，不得重複訴訟。",
                "cited_authority": {
                    "type": "case",
                    "label": "Henderson v Henderson (1843)",
                },
            },
        ],
        "relationships": [
            {
                "type": "APPLIES",
                "target_type": "case",
                "target_label": "Henderson v Henderson (1843)",
                "description": "Applies the one-stop litigation principle to repeat proceedings.",
            },
        ],
    },
]
